### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by zajavzek** [chilledHamza/Hackintosh_Legion_Y530#6] opened 2021-11-29 21:02 UTC
Unfortunately, in the latest update, bluetooth does not work, it turns on devices, but connects to them only for a second. Probably because of this, unlocking with the watch does not work.
Besides, video like apple TV + and netflix in safari doesn't work

**Comment by chilledHamza** [comment] 2021-11-30 08:11
Duplicate of #4 

> Unfortunately, in the latest update, bluetooth does not work, it turns on devices, but connects to them only for a second. Probably because of this, unlocking with the watch does not work.

Bluetooth have some issues on Monterey. If Bluetooth functionality is important to you, consider downgrading to Big Sur. I have tested AirDrop and it worked fine on my end. 
[BlueToolFixup has known issues with beta 5+](https://github.com/acidanthera/bugtracker/issues/1821)

> Besides, video like apple TV + and netflix in safari doesn't work

DRM content requires AMD GPU. Have a look at [DRM Compatibility Chart](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md), also don't forget to read notes about macOS 11+

**Closed by chilledHamza** 2021-11-30 08:11 UTC
Labels: duplicate
